import type { Metadata } from "next";
import type { CSSProperties } from "react";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { BrandingProvider } from "@/components/BrandingProvider";

const fontVariables = {
  "--font-geist-sans": '"Inter", "Helvetica Neue", Arial, sans-serif',
  "--font-geist-mono": '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
  "--font-playfair": '"Georgia", "Times New Roman", serif',
  "--font-inter": '"Inter", "Helvetica Neue", Arial, sans-serif',
} as CSSProperties;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased font-sans"
        style={fontVariables}
        suppressHydrationWarning
      >
        <BrandingProvider>
          {children}
        </BrandingProvider>
      </body>
    </html>
  );
}
